## Linear Regression

import

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [7]:
x=[4,5,6,7]
y=[420,440,480,500]

data split

In [8]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30,random_state=1)

linear regression

In [ ]:
reg=LinearRegression()
reg.fit(xtrain,ytrain)
reg.predict(xtest)

predict

In [ ]:
reg.predict([[45]])

c:\Users\SADMAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[1376.83363148]])

Coef_ and Intercept_

In [ ]:
reg.coef_

array([[23.38103757]])

In [ ]:
reg.intercept_

array([324.68694097])